# 站点配置
baseURL = "https://newdivide2014.github.io"
title = "蓝红柿的小站"
theme = "FixIt"

# i18n
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true

enableEmoji = true
enableRobotsTXT = true
buildDrafts = false
summaryLength = 150

[taxonomies]
  _merge = "shallow"
