##########################################
# 菜单配置

# MemE 主题支持以下四种菜单：
# 1. main       顶栏下方（居中布局）或里面（弹性
#               布局）的菜单栏
# 2. home       首页的底部链接（适用于「诗意
#               人生」和「视频片段」布局）
# 3. socials    社交栏（关于页面的极简页脚）
# 4. links      链接栏（关于页面的极简页脚）

# 菜单内的配置说明如下：
# url           链接地址
# name          文本（留空（""）则无）
# weight        位置
# pre           内链（internal）或外链（external）
# post          图标（留空（""）则无）
# identifier    图标的 Class 名
#               （对于弹性布局的顶栏有三个特殊
#               的值：`theme-switcher`、
#               `lang-switcher`、`search`）

# [menu]
    ## 菜单栏
    # [[menu.main]]
    #     url = "/"
    #     name = "首页"
    #     weight = 1
    #     pre = "internal"
    #     post = "home"
[[main]]
        url = "/en/posts/"
        name = "Posts"
        weight = 2
        pre = "internal"
        post = "archive"
[[main]]   
        url = "/en/categories/"
        name = "Categories"
        weight = 3
        pre = "internal"
        post = "th"
[[main]]   
        url = "/en/tags/"
        name = "Tags"
        weight = 4
        pre = "internal"
        post = "tags"
[[main]]   
        url = "/en/about/"
        name = "About"
        weight = 5
        pre = "internal"
        post = "user-circle"
[[main]]   
        weight = 7
        identifier = "theme-switcher"
[[main]]   
        weight = 6
        identifier = "lang-switcher"