main:
                - name: Search
                  url: search/
                  weight: 5
                - name: Archives
                  url: archives/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 15
                - name: Categories
                  url: categories/
                  weight: 20
