main:
                - name: 搜索
                  url: search/
                  weight: 5
                - name: 归档
                  url: archives/
                  weight: 10
                - name: 标签
                  url: tags/
                  weight: 15
                - name: 分类
                  url: categories/
                  weight: 20
                - name: 关于
                  url: about/
                  weight: 25
